# Generated by Django 4.2.7 on 2026-04-09 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("branches", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskinstance",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_instances",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Asignado a",
            ),
        ),
        migrations.AddField(
            model_name="taskinstance",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_instances",
                to="branches.branch",
                verbose_name="Sucursal",
            ),
        ),
        migrations.AddField(
            model_name="taskinstance",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="tasks.task",
                verbose_name="Tarea",
            ),
        ),
        migrations.AddField(
            model_name="taskchecklistitem",
            name="checklist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instance_items",
                to="tasks.taskchecklist",
                verbose_name="Ítem de checklist",
            ),
        ),
        migrations.AddField(
            model_name="taskchecklistitem",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_checklist_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Completado por",
            ),
        ),
        migrations.AddField(
            model_name="taskchecklistitem",
            name="task_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist_items",
                to="tasks.taskinstance",
                verbose_name="Instancia de tarea",
            ),
        ),
        migrations.AddField(
            model_name="taskchecklist",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist_items",
                to="tasks.task",
                verbose_name="Tarea",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Asignado a",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="branches.branch",
                verbose_name="Sucursal",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.taskmodule",
                verbose_name="Módulo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskchecklistitem",
            unique_together={("checklist", "task_instance")},
        ),
    ]
