# Generated by Django 4.2.7 on 2026-04-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskchecklistitem",
            name="comment",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Comentario"
            ),
        ),
    ]
