# Generated by Django 4.2.7 on 2026-04-09 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("crear", "Crear"),
                            ("actualizar", "Actualizar"),
                            ("completar", "Completar"),
                            ("eliminar", "Eliminar"),
                            ("asignar", "Asignar"),
                            ("iniciar", "Iniciar"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                        ],
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(max_length=50, verbose_name="Tipo de contenido"),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID del objeto"
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Valores anteriores"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Valores nuevos"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="branches.branch",
                        verbose_name="Sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "ordering": ["-timestamp"],
            },
        ),
    ]
