# Generated by Django 4.2.7 on 2026-04-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient",
                    models.EmailField(max_length=254, verbose_name="Destinatario"),
                ),
                ("subject", models.CharField(max_length=300, verbose_name="Asunto")),
                ("body", models.TextField(verbose_name="Cuerpo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Error")),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviado en"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log de email",
                "verbose_name_plural": "Logs de emails",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("message", models.TextField(verbose_name="Mensaje")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task", "Tarea"),
                            ("alert", "Alerta"),
                            ("system", "Sistema"),
                        ],
                        default="task",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Leída")),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(max_length=20, verbose_name="Destinatario"),
                ),
                ("message", models.TextField(verbose_name="Mensaje")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Error")),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviado en"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log de WhatsApp",
                "verbose_name_plural": "Logs de WhatsApp",
                "ordering": ["-created_at"],
            },
        ),
    ]
